polls/config/urls.py
from django.contrib import admin
from django.urls import path, include
from poll import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls')),
    path('', views.index),
]

polls/poll/urls.py
from django.urls import path
from . import views
# 네임스페이즈(이름 공간)
app_name = 'poll'

urlpatterns = [
    #http://127.0.0.1.8000/poll/
    path("", views.poll_list, name='poll_list'),
    # http://127.0.0.1.8000/poll/1
    path("<int:question_id>/", views.detail, name='detail'),
    # http://127.0.0.1.8000/poll/1/vote
    path("<int:question_id>/vote/", views.vote, name='vote'),

    #http://127.0.0.1.8000/poll/test
    path("test/", views.test),
]

polls/poll/models.py
from django.db import models

# 질문 테이블(모델)
class Question(models.Model):  # 상속관계
    # 필드
    question_text = models.CharField(max_length=200)  # 영어 기준
    pub_date = models.DateTimeField()
    
    def __str__(self):  # 객체 정보를 문자열로 반환
        return self.question_text

# 항목 테이블(엔티티)
class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

polls/poll/views.py
from django.http import HttpResponse
from django.shortcuts import render
from poll.models import Question

def index(request):
    return render(request, 'poll/index.html')

def poll_list(request):
    # 전체 데이터 가져오기
    question_list = Question.objects.all()
    return render(request, 'poll/poll_list.html', {'question_list': question_list})
    # return HttpResponse("<h1>안녕~Poll!</h1>")

def detail(request, question_id):
    # 데이터 1개 조회
    question = Question.objects.get(id=question_id)
    return render(request, 'poll/detail.html', {'question': question})

# 투표하기
def vote(request, question_id):
    question = Question.objects.get(id=question_id)

    if request.method == "POST":
        try:
            choice_id = request.POST['choice'] # 선택된 항목 id
            sel_choice = question.choice_set.get(id=choice_id) #id로 항목을 찾아서
        except:
            error = "선택을 하지 않았습니다."
            return render(request, 'poll/detail.html',
                          {'question': question, 'error': error})
        else:
            sel_choice.votes = sel_choice.votes + 1 # sel_choice.votes= 0
            sel_choice.save() # 저장 필수
            return render(request, 'poll/result.html', {'question': question})
    else: #GET
        return render(request, 'poll/detail.html', id=question_id)

def test(request):
    cart = "콩나물"  # 모델(데이터) - 딕셔너리형으로 보냄
    cartlist = ["계란", "콩나물", "생수", "커피"]
    context = {'cart': cart, 'cartlist': cartlist}
    return render(request, 'poll/test.html', context)

polls/templates/poll/detail.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>설문 항목</title>
</head>
<body>
    <h1>설문 항목</h1>
    <form action = "{% url 'poll:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            {% if error %}
                {{ error }}
            {% endif %}
            <legend>{{ question.question_text }}</legend>
            {% for choice in question.choice_set.all %}
            <p>
                <input type="radio" name="choice" value="{{ choice.id }}">
                <label>{{ choice.choice_text }}</label>
            </p>
            {% endfor %}
        </fieldset>
        <p><input type="submit" value="투표"></p>
    </form>


    <!--<ul>
        {% for choice in question.choice_set.all %}
        <li>choice.choice_text</li>
        {% endfor %}
    </ul>-->
</body>
</html>

polls/templates/poll/index.html
<!DOCTYPE html>
<html lang="ko">
<!-- static 적용하려면 필수로 명시해야함-->
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>main 페이지</title>
    <link rel="stylesheet" href="{% static 'poll/css/style.css' %}">
</head>
<body>
    <div id="container">
        <section id="main">
            <div class="poll">
                <a href="{% url 'poll:poll_list %}">
                    <img src="{% static 'poll/images/vote.png' %}" alt="투표">
                    <p>설문 투표 바로가기</p>
                </a>
            </div>
            <div class="ocr">
                <a href="">
                    <img src="{% static 'poll/images/ocr.png' %}" alt="ocr">
                    <p>설문 투표 바로가기</p>
                </a>
            </div>

        </section>
    </div>
</body>
</html>

polls/templates/poll/poll_list.html
<!DOCTYPE html>
<html lang="ko">
<!-- static 적용하려면 필수로 명시해야함-->
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>main 페이지</title>
    <link rel="stylesheet" href="{% static 'poll/css/style.css' %}">
</head>
<body>
    <div id="container">
        <section id="poll_list">
            <h1>설문 목록</h1>
            <ul>
                {% for question in question_list %}
                <li>
                    <a href="{% url 'poll:detail' question.id %}">
                    {{ question.question_text }}
                    </a>
                </li>

                {% endfor %}
            </ul>
            {% else %}
                <p>설문이 없습니다.</p>
            {% endif %}
            <img src="{% static 'poll/images/vote.png' %}" alt="투표">
        </section>
    </div>
</body>
</html>

polls/templates/poll/result.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>투표 결과</title>
    <link rel="stylesheet" href="{% static 'poll/css/style.css' %}">
</head>
<body>
    <div id="container">
        <section id="result">
            <h1>투표 결과</h1>
            <h3>{{ question.question_text }}</h3>
            <ul>
                {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }} -- {{ choice.votes }}</li>
                {% endfor %}
            </ul>
        </section>
    </div>
</body>
</html>

polls/templates/poll/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Model Test</title>
</head>
<body>
  <h3>{{ cart }}</h3>
    <ul>
        {% for cart in cartlist %}
        <li>{{ cart }}</li>
        {% endfor %}
    </ul>
</body>
</html>