blogs/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),  # 목록
    path('<int:post_id>/', views.detail, name='detail'),  # 상세페이지
    path('post/create/', views.post_create, name='post_create'),  #  이 이 이 이 이 이 이 이 이 이 이 이 이 이 이 이 이 이 이 이 이 이 이 이
]

blogs/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),  # http://127.0.0.1:8000/
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

blogs/blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=100)  # 제목
    content = models.TextField()  # 내용
    pub_date = models.DateTimeField()  # 발행일
    modify_date = models.DateTimeField(null=True, blank=True)  # 입력 폼이 비어도 됨(blank=True)
    photo = models.ImageField(upload_to='blog/images/%Y/%m/%d/',
                              null=True, blank=True)  # null 허용, 파일을 첨부하지 않을수 있음

    def __str__(self):
        return self.title

blogs/blog/forms.py
from django import forms

from blog.models import Post


# 포스트 폼 생성
class PostForm(forms.ModelForm):
    class Meta:
        model = Post  # Post 객체 생성
        fields = ['title', 'content', 'photo']
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea)
    photo = forms.ImageField()

blogs/blog/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from .forms import PostForm
from .models import Post

def index(request):
    return render(request, 'blog/index.html')

# 포스트 목록
def post_list(request):
    post_list = Post.objects.all()
    context = {'post_list': post_list}
    return render(request, 'blog/post_list.html', context)

# 상세 페이지
def detail(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {'post': post}
    return render(request, 'blog/detail.html', context)

# 글쓰기
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)  # (일반속성, 파일)
        if form.is_valid():  # 유효하다면
            post = form.save(commit=False)
            post.pub_date = timezone.now()  # 현재 시간
            post.save()
            return redirect('blog:post_list')
    else:
        form = PostForm()  # 비어있는 폼
    context = {'form': form}
    return render(request, 'blog/post_form.html', context)

blogs/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <script src="{% static 'blog/js/bootstrap.js' %}"></script>
</head>
<body>
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</body>
</html>

blogs/templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h3>{{ post.title }}</h3>
    <h5 style="white-space: pre-line; line-height: 1.5em">
        {{ post.content }}
    </h5>
    <p>(작성일: {{ post.pub_date }})</p>
</div>
{% endblock %}

blogs/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container my-3">
    <h1>Blog에 오신 것을 환영합니다.</h1>
    <img src="{% static 'blog/images/activity.jpg' %}" alt="패러글라이딩">
</div>
{% endblock %}

blogs/templates/blog/post_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h3>글쓰기</h3>
    <form action="" method="post"
          enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
        <button type="submit">저장하기</button>
    </form>

</div>
{% endblock %}

blogs/templates/blog/post_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Blog 홈</h1>
    {% if post_list %}
        <!-- 포스트 가져옴 -->
        {% for post in post_list %}
            <h3>
                <a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a>
            </h3>
            <h5 style="white-space: pre-line; line-height: 1.5em">
                {{ post.content }}
            </h5>
            <p>(작성일: {{ post.pub_date }})</p>
            {% if post.photo %}
            <img src="{{ post.photo.url }}">
            {% endif %}
        {% endfor %}
    {% else %}
        <p>포스트가 없습니다.</p>
    {% endif %}
</div>
{% endblock %}

blogs/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">PyBlog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">로그인</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_create' %}">글쓰기</a>
        </li>

      </ul>
    </div>
  </div>
</nav>